# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "/"
baseurl: "/"
siteIcon: /logo.png
siteYear: 2023
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: Eclipse Pixel
serverDescription: Join the Eclipse Pixel Adventure!
serverIP: Coming Soon!
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/7ABzvWjyTM
discordServerID: 1141830157129240576
discordChannelID: 1150664157901893694


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
siteNav:
   - name: Rules
     url: rules
   - name: Leaks
     url: leaks
     newtab: false
   - name: Application
     url: application
   - name: About
     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
